#ifndef _CARD_TYPE_H_
#define _CARD_TYPE_H_

enum CardType
{
	CARD_TYPE_NONNIU     = 0,  // 没牛
	CARD_TYPE_NIUDING    = 1,
	CARD_TYPE_NIUER      = 2,
	CARD_TYPE_NIUSAN     = 3,
	CARD_TYPE_NIUSI      = 4,
	CARD_TYPE_NIUWU      = 5,
	CARD_TYPE_NIULIU     = 6,
	CARD_TYPE_NIUQI	     = 7,
	CARD_TYPE_NIUBA	     = 8,
	CARD_TYPE_NIUJIU	  = 9,
	CARD_TYPE_NIUNIU	  = 10,
    CARD_TYPE_ZHADAN	  = 11,
	CARD_TYPE_JINNIU	  = 12,
	CARD_TYPE_WUXIAONIU	  = 13,
};

enum CardRatio
{
	CARD_RATIO_LESS    = 1,
    CARD_RATIO_QI      = 2,
	CARD_RATIO_NIUBA   = 2,
	CARD_RATIO_NIUJIU  = 2,
	CARD_RATIO_NIUNIU  = 3,
	CARD_RATIO_ZHADAN  = 4,
    CARD_RATIO_JINNIU  = 5,
	CARD_RATIO_WUXIAONIU  = 6,

	CARD_RATIO_MAX = CARD_RATIO_WUXIAONIU,
};

#endif /* _CARD_TYPE_H_ */
